import { Raleway } from 'next/font/google';
import './globals.css';

const raleway = Raleway({ style: ['normal', 'italic'], subsets: ['latin'], variable: '--font-poppins', display: 'swap', weight: ['400', '700', '600'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className + ' bg-customBg'}>
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
